# Generated by Django 5.2.6 on 2025-09-22 05:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('prefectures', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('time_min', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.IntegerField(default=2)),
                ('seasonality', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('gmaps_url', models.URLField(blank=True, default='')),
                ('geom_geojson', models.JSONField(blank=True, null=True)),
                ('name_i18n', models.JSONField(blank=True, default=dict)),
                ('description_i18n', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
